/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffbe1c",
        "secondary": "#fff3d5",
        "landback": "#111611",
        "gdc-orange": "#E66A1C",
        "gdc-yellow": "#F8BE1E",
      },
      keyframes: {
        glitch1: {
          '0%': { clipPath: 'rect(132px, auto, 101px, 30px)' },
          '5%': { clipPath: 'rect(17px, auto, 94px, 30px)' },
          '10%': { clipPath: 'rect(40px, auto, 66px, 30px)' },
          '15%': { clipPath: 'rect(87px, auto, 82px, 30px)' },
          '20%': { clipPath: 'rect(137px, auto, 61px, 30px)' },
          '25%': { clipPath: 'rect(34px, auto, 14px, 30px)' },
          '30%': { clipPath: 'rect(133px, auto, 74px, 30px)' },
          '35%': { clipPath: 'rect(76px, auto, 107px, 30px)' },
          '40%': { clipPath: 'rect(59px, auto, 130px, 30px)' },
          '45%': { clipPath: 'rect(29px, auto, 84px, 30px)' },
          '50%': { clipPath: 'rect(22px, auto, 67px, 30px)' },
          '55%': { clipPath: 'rect(67px, auto, 62px, 30px)' },
          '60%': { clipPath: 'rect(10px, auto, 105px, 30px)' },
          '65%': { clipPath: 'rect(78px, auto, 115px, 30px)' },
          '70%': { clipPath: 'rect(105px, auto, 13px, 30px)' },
          '75%': { clipPath: 'rect(15px, auto, 75px, 30px)' },
          '80%': { clipPath: 'rect(66px, auto, 39px, 30px)' },
          '85%': { clipPath: 'rect(133px, auto, 73px, 30px)' },
          '90%': { clipPath: 'rect(36px, auto, 128px, 30px)' },
          '95%': { clipPath: 'rect(68px, auto, 103px, 30px)' },
          '100%': { clipPath: 'rect(14px, auto, 100px, 30px)' },
        },
        glitch2: {
          '0%': { clipPath: 'rect(129px, auto, 36px, 30px)' },
          '5%': { clipPath: 'rect(36px, auto, 4px, 30px)' },
          '10%': { clipPath: 'rect(85px, auto, 66px, 30px)' },
          '15%': { clipPath: 'rect(91px, auto, 91px, 30px)' },
          '20%': { clipPath: 'rect(148px, auto, 138px, 30px)' },
          '25%': { clipPath: 'rect(38px, auto, 122px, 30px)' },
          '30%': { clipPath: 'rect(69px, auto, 54px, 30px)' },
          '35%': { clipPath: 'rect(98px, auto, 71px, 30px)' },
          '40%': { clipPath: 'rect(146px, auto, 34px, 30px)' },
          '45%': { clipPath: 'rect(134px, auto, 43px, 30px)' },
          '50%': { clipPath: 'rect(102px, auto, 80px, 30px)' },
          '55%': { clipPath: 'rect(119px, auto, 44px, 30px)' },
          '60%': { clipPath: 'rect(106px, auto, 99px, 30px)' },
          '65%': { clipPath: 'rect(141px, auto, 74px, 30px)' },
          '70%': { clipPath: 'rect(20px, auto, 78px, 30px)' },
          '75%': { clipPath: 'rect(133px, auto, 79px, 30px)' },
          '80%': { clipPath: 'rect(78px, auto, 52px, 30px)' },
          '85%': { clipPath: 'rect(35px, auto, 39px, 30px)' },
          '90%': { clipPath: 'rect(67px, auto, 70px, 30px)' },
          '95%': { clipPath: 'rect(71px, auto, 103px, 30px)' },
          '100%': { clipPath: 'rect(83px, auto, 40px, 30px)' },
        },
        rotation: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        btnhover: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)', boxShadow: '2px 2px 3px #333333' },
          '100%': { transform: 'scale(1)' },
        }
      },
      animation: {
        'glitch-1': 'glitch1 2.5s linear infinite',
        'glitch-2': 'glitch2 2.5s linear infinite reverse',
        'rotation': 'rotation 15s linear infinite',
        'btnhover': 'btnhover 0.7s ease-in-out',
      }
    },
    fontFamily: {
      mfont: ["Black Ops One", "system-ui"],
      navfont: ["Orbitron", "sans-serif"],
      title: ["Press Start 2P", "system-ui"],
      subtitle: ["Wallpoet", "sans-serif"],
      pacfont: ["pacfont", "sans-serif"],
      Syne: ["Syne", "sans-serif"],
      drover: ["drover", "sans-serif"],
      space: ["space", "sans-serif"],
      valorant: ["valorant", "sans-serif"],
      planet: ["Planet", "sans-serif"],
      nico: ["nico", "sans-serif"],
    }
  },
  plugins: [],
};
